### PR TITLE
Fix errors in content

### PR DESCRIPTION
**Pull request by DrSmugleaf**

### CODE REVIEW

**Review by Clyybber — APPROVED** [review]
b

**Review by gradientvera — APPROVED** [review]
I have, 100 %, looked at all these files and approve of this PR.

**Review by Clyybber — APPROVED** [review]

**Review by AJCM-git — APPROVED** [review]
gus

**Review by gradientvera — APPROVED** [review]
amo

**Review by AJCM-git — APPROVED** [review]

**Review by AJCM-git — APPROVED** [review]

**Review by AJCM-git — APPROVED** [review]

**Review by AJCM-git — APPROVED** [review]

**Comment by PaulRitter** [comment]
good first pr

**Pull request merged**
